### ISSUE TITLE
Style the styleguide

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#25]
...ideally using Nautilus itself, not to get _too_ recursive about it or anything. (I may need some help doing that!)

**Comment by tofumatt** [comment]
It turns out this was a _bit_ difficult to uncover, because while the docs mention the ability to change out any of the React-Styleguidist components, there isn't a clear/obvious list right away.

Turns out [every component in this folder](https://github.com/styleguidist/react-styleguidist/tree/master/src/client/rsg-components) can be replaced like we're doing for the `Wrapper` component here: https://github.com/octopusthink/nautilus/blob/master/styleguide.config.js#L29.

The trick is to replace it with the component we want to use based on its name in RSG: https://github.com/styleguidist/react-styleguidist/tree/master/src/client/rsg-components

We can examine those components in RSG to see what props they take. It might be that we have to make a `StyleguideHeading` component to map RSG's props to ours, but that's not a huge task.

**Comment by tofumatt** [comment]
Keeping this open as #38 was just the beginning…
